### ISSUE TITLE
Looks like the reorder section doesn't have a good example in it. 

### ISSUE THREAD

**Issue by jcbbuller** [vapid/vapid-docs#7]
This is all that it shows:

`<code>
  

  &lt;article class="post"&gt;
    
    &lt;header&gt;&lt;/header&gt;
    &lt;div class="summary"&gt;&lt;/div&gt;
  &lt;/article&gt;

</code>`

**Comment by srobbin** [comment]
@jcbbuller Just pushed a fix. Thanks for letting me know.
